### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by 993739033** [webdev-support/chrome_content_shell#1]
Hi Sir, I would like to know how you exported the chroium source code as an android executable project. 
I now have the same version of the source code, 
but I don't know how to export the project like you do.
The above is from translation software
thanks!

**Comment by jeesk** [comment]
参考这个项目: 
https://github.com/chromium/chromium/blob/main/content/shell/android/BUILD.gn
BUILD.gn 就是项目构建配置, 直接构建chromium content shell 了, 如果要提取出来, 将BUILD.gn 的资源提取出来就行了.

**Comment by webdev-support** [comment]
有2种方法


1. 参考这个项目:
https://github.com/chromium/chromium/blob/main/content/shell/android/BUILD.gn
BUILD.gn 就是项目构建配置, 直接构建chromium content shell 了, 如果要提取出来, 将BUILD.gn 的资源提取出来就行了. 

2. 反编译chromium 相关的apk

**Comment by 993739033** [comment]
学到了，我现在能编译出chromium apk就是不知道怎么导出项目。
有这个真的帮大忙了。非常感谢！

**Comment by XiGuaShuai** [comment]
我现在 只反编译去 按照目录去 抽取 类，太麻烦了 ，几千个文件

**Comment by webdev-support** [comment]
> 我现在 只反编译去 按照目录去 抽取 类，太麻烦了 ，几千个文件

chroium 项目耗时费力的，加油吧
